### ISSUE TITLE
[用户邮件反馈]希望在杭电导航（指南）中添加校园警卫电话。

### ISSUE THREAD

**Issue by qianlongzt** [hduhelper/HDU-Guide#7]
> 今天发现有很多导航这个东西，挺不错的。但是我希望在维权这个界面加入校园警卫的电话。
> 因为我公告有事情想报警来着，但是不知道号码多少，进了杭电助手找了半天也是没有找到号码多少，让我有些失望。
> 希望能加入校园警卫电话！因为真正紧急的时候，报警最有用。

**Comment by lxwzy** [comment]
参考 [保卫处网站](http://baowei.hdu.edu.cn/) ，已在 3249e1b21fca7366387849d8fbc2c8bdbeed16c8 中增加
